Feature/multiple statement
flinters/digdag_operator_snowflake pull request #27
Opened 2023-02-16 04:32 UTC by kanaeta

## 変更内容
- queryオプションを追加し、sqlファイルではなく、直にsqlを書けるようにした　https://github.com/flinters/digdag_operator_snowflake/commit/d3083fc0958e6755826f505fd4bb9e3b0cd4bc5f
- 実行時にdigdagへの戻り値としてqueryのIDを渡すようにした https://github.com/flinters/digdag_operator_snowflake/commit/d51bebd57d6b736c2cc97bff5a0293a0b0b0a687
- multi_queriesオプションを追加し、複数文を実行できるようにした [d51bebd..d695327](https://github.com/flinters/digdag_operator_snowflake/compare/d51bebd..d695327)

### 実行サンプル

以下のようなクエリを実行しました
![スクリーンショット 2023-02-16 13 21 45](https://user-images.githubusercontent.com/3855099/219267880-d9e71a6b-3674-43ee-a7a5-907cd93e33f9.png)

1. 戻り値の確認
digdagのコンソール画面でsnow.last_queryに戻り値が格納されている
![スクリーンショット 2023-02-16 13 23 51](https://user-images.githubusercontent.com/3855099/219268205-a405530f-0098-48d2-b35a-8086fc67a9d1.png)

2. TEMPORARY TABLEを使用できるかの確認
TEST1テーブルからデータを抽出できている
![スクリーンショット 2023-02-16 13 27 55](https://user-images.githubusercontent.com/3855099/219268672-8aafb126-a5eb-4921-9e46-16e9b4545f25.png)

3. TRANSACTIONが効いてるかの確認
失敗した際は成功したものも格納されてない
![スクリーンショット 2023-02-16 13 25 42](https://user-images.githubusercontent.com/3855099/219268992-556d71dd-b0df-489f-8cc2-35e86805a56c.png)

2023-02-16 05:02 UTC, tkawachi commented
もしテストがかけそうならチャレンジしてほしいです。

2023-02-16 05:45 UTC, kanaeta commented
> 

(単体テストに絞って話します)

すみません、これに関しては参考にした [digdag-operator-athena](https://tech.gunosy.io/entry/introduce-digdag-plugins#digdag-operator-athena) や [digdag-slack](https://github.com/szyn/digdag-slack) にexsampleはあれどtestがなく、正直どう手をつければ良いかわかりませんでした。

ただ他のpluginを調べてみたら、門脇さんが作成したpluginにテストがありました。 [digdag-plugin-datadog](https://github.com/NomadBlacky/digdag-plugin-datadog/tree/master/src/test)   
まだ読み解いている段階ですが、これはユーザーが入力したパラメータで予期せぬものがあった場合の挙動確認が大半でしょうか?

今回そこまで複雑なドメインロジックを追加した認識はあまりないですが、単体テストとして有効そうなのは、`レスポンスを上手に処理し期待したoutput parametersを抽出できているかどうか`  などでしょうか？

2023-02-17 01:29 UTC, kanaeta commented on README.md
> +`multi_queries`|x|複数のクエリを実行可にする場合(true|false). SQLインジェクションを受ける可能性が高くなるため使用には注意|o|o|x
以下のような注釈があるため、デフォルトで複数クエリを実行できるようにするのではなく、利用側での使用判断できるように、オプションでの提供にしました。

https://docs.snowflake.com/ja/user-guide/jdbc-using#multi-statement-support 

```
注釈

デフォルトでは、Snowflakeは、複数のステートメントで発行されたクエリに対してエラーを返します。
この動作は、 [SQL インジェクション](https://en.wikipedia.org/wiki/SQL_injection) から保護するために部分的に行われます。
複数ステートメント機能を使用すると、 SQL インジェクションを受ける可能性があるため、慎重に使用する必要があります。 
SnowflakeStatement クラスのsetParameter（）メソッドを使用して実行するステートメントの数を指定することにより、ステートメントを追加して注入することがより困難になるため、リスクを軽減できます。詳細については、 [インターフェイス： SnowflakeStatement](https://docs.snowflake.com/ja/user-guide/jdbc-api.html#label-jdbc-snowflakestatement) をご参照ください。
```

2023-02-17 01:29 UTC, kanaeta commented on src/main/scala/dev/hiro_hori/digdag_operator_snowflake/SnowOperator.scala
> +      // @see https://docs.snowflake.com/en/user-guide/jdbc-using.html#multi-statement-support
複数のクエリを発行する場合は、1つ１つのクエリに分割されて実行されます。

その際に、全てのクエリIDを取得することができませんでした。

ex.) begin transactionやinsert into .. ; ddl系などが取得できないものだと思います

実行サンプルのtest1:タスクにおいても取得できたのは、最初の1つと `select * ...`の2つで合計3つのクエリIDのみです。

*補足*

一文だけの実行ならどんなものでもクエリIDを取得できます。

2023-02-17 01:29 UTC, kanaeta commented on src/main/scala/dev/hiro_hori/digdag_operator_snowflake/SnowOperator.scala
> +      workspace.templateCommand(templateEngine, config, "query", UTF_8)
補足ですが、templateCommandの内部実装を見るとtemplateFileを拡張したもので、いままでの _command によるsqlファイルの受け渡しもできます。

2023-02-17 01:31 UTC, kanaeta commented
> もしテストがかけそうならチャレンジしてほしいです。

2023-02-17 02:28 UTC, tkawachi commented on src/main/scala/dev/hiro_hori/digdag_operator_snowflake/SnowOperator.scala
> +  protected def buildOutputParam(sql: String, queries: List[QueryResult]): Config =
private のほうが良さそう。

2023-02-17 02:28 UTC, tkawachi commented on src/main/scala/dev/hiro_hori/digdag_operator_snowflake/SnowOperator.scala
> +      // @see https://docs.snowflake.com/en/user-guide/jdbc-using.html#multi-statement-support
> 実行サンプルのtest1:タスク

test1 の定義はどこでしょうか？

2023-02-17 02:28 UTC, tkawachi commented on src/main/scala/dev/hiro_hori/digdag_operator_snowflake/SnowOperator.scala
> +      // stmt.getMoreResultsは値がない場合など機能しない。そのため何個のクエリが実行されたか知る方法がなく、";"をカウントして代わりとした
> stmt.getMoreResultsは値がない場合など機能しない。

値がない場合というのは上にコメントのあった

> begin transactionやinsert into .. ; ddl系など

という認識であっていますか？

また、 その場合の機能しないと言うのは false が返るということでしょうか？それとも例外が発生するということでしょうか？

2023-02-17 02:39 UTC, kanaeta commented on src/main/scala/dev/hiro_hori/digdag_operator_snowflake/SnowOperator.scala
> +      // @see https://docs.snowflake.com/en/user-guide/jdbc-using.html#multi-statement-support
こちらの添付ファイルの+test1部分です。
https://user-images.githubusercontent.com/3855099/219267880-d9e71a6b-3674-43ee-a7a5-907cd93e33f9.png

発行したクエリはこちらになります。
```
CREATE TEMPORARY TABLE TEST1 (col1 VARCHAR, col2 BIGINT);
INSERT INTO TEST1 (col1, col2) VALUES ('a',1);
SELECT * FROM TEST1;

CREATE TABLE TEST2 (col1 VARCHAR, col2 BIGINT);
INSERT INTO TEST2 (col1, col2) VALUES ('b',2);
SELECT * FROM TEST2;
```

2023-02-17 02:42 UTC, kanaeta commented on src/main/scala/dev/hiro_hori/digdag_operator_snowflake/SnowOperator.scala
> +  protected def buildOutputParam(sql: String, queries: List[QueryResult]): Config =
こちらはそうですね、ありがとうございます

[digdag-operator-athena](https://tech.gunosy.io/entry/introduce-digdag-plugins#digdag-operator-athena) からパクったのですが、こちらは基底となるクラスがあるためprotectedになってますが、現状snowflakeでは必要ないですね

2023-02-17 02:46 UTC, kanaeta commented on src/main/scala/dev/hiro_hori/digdag_operator_snowflake/SnowOperator.scala
> +      // stmt.getMoreResultsは値がない場合など機能しない。そのため何個のクエリが実行されたか知る方法がなく、";"をカウントして代わりとした
> begin transactionやinsert into .. ; ddl系など
> という認識であっていますか？
はい、その通りです。

getMoreResultsでfalseが帰ってきます。

例えば上記の
```
CREATE TEMPORARY TABLE TEST1 (col1 VARCHAR, col2 BIGINT);
INSERT INTO TEST1 (col1, col2) VALUES ('a',1);
SELECT * FROM TEST1;

CREATE TABLE TEST2 (col1 VARCHAR, col2 BIGINT);
INSERT INTO TEST2 (col1, col2) VALUES ('b',2);
SELECT * FROM TEST2;
```
だとgetMoreResultsは呼び出すたびに、false,false,true,false,false,true,(以降はずっとfalse)が帰ってきます

2023-02-17 02:55 UTC, kanaeta commented on src/main/scala/dev/hiro_hori/digdag_operator_snowflake/SnowOperator.scala
> +  protected def buildOutputParam(sql: String, queries: List[QueryResult]): Config =
修正しました

2023-02-17 07:23 UTC, tkawachi requested changes

2023-02-17 07:23 UTC, tkawachi commented on src/main/scala/dev/hiro_hori/digdag_operator_snowflake/SnowOperator.scala
> +      // stmt.getMoreResultsは値がない場合など機能しない。そのため何個のクエリが実行されたか知る方法がなく、";"をカウントして代わりとした
なるほど。あとから読む人がわかりやすいように、コメントで説明をお願いします。
書いておいてほしいポイントは

- CREATE TABLE 文などで getMoreResults が false を返す
- getMoreResults 以外に statement をイテレーションする手段が見つからない

（したがって ; の数を数えて、loop している）

2023-02-17 07:23 UTC, tkawachi commented on src/main/scala/dev/hiro_hori/digdag_operator_snowflake/SnowOperator.scala
> +      }.toList
; の数だけ loop して mutable に値を詰めているだけなので、 `.foldLeft` より `(0 until maxStmt).foeach()` で回して `.add()` していったほうが読みやすいように思います。

maxStmt 回だけ loop するなら `0 to maxStmt` ではなく `0 until maxStmt` ですね。

2023-02-17 07:23 UTC, tkawachi commented on src/main/scala/dev/hiro_hori/digdag_operator_snowflake/SnowOperator.scala
> +      val maxStmt = sql.count(_ == ';')
変数名から察するに、これは最大の statement 数、という意味ですよね。

確認してほしいのですが、最後に `;` がない場合に誤った数になりませんか？例えばつぎのように

```
INSERT INTO T VALUES (1);
INSERT INTO T VALUES (2)
```

https://docs.snowflake.com/en/user-guide/jdbc-using.html#multi-statement-support  の例に最後に `;` をふくまない例があったので気になります。

```java
// Create a string that contains multiple SQL statements.
String command_string = "create table test(n int); " +
                        "insert into test values (1), (2); " +
                        "select * from test order by n";
```

2023-02-17 07:26 UTC, tkawachi commented on src/main/scala/dev/hiro_hori/digdag_operator_snowflake/SnowOperator.scala
> +  protected def buildOutputParam(sql: String, queries: List[QueryResult]): Config =
protected を消すと public になります。外から使う想定はないので private つけてあげたほうが良さそうですね。

2023-02-17 07:42 UTC, kanaeta commented on src/main/scala/dev/hiro_hori/digdag_operator_snowflake/SnowOperator.scala
> +  protected def buildOutputParam(sql: String, queries: List[QueryResult]): Config =
すみません、これ完全に勘違いして覚えてました..

他のpublicなのもの全てprivateにします

2023-02-17 07:46 UTC, so-tomoshira commented on README.md
> +`query`|x|ファイルではなくクエリを直接記載|o|x|x
説明の書きっぷりに関して、
> ファイルではなくクエリを直接記載

よりもシンプルに「クエリを直接記載」で十分だと思った次第です。

---

@kanaeta 
質問：  
クエリ内に変数（`${...}`）を利用することは可能ですか？  
（可能な場合、その旨を説明書きに記載いただけると、よりわかりやすいと思った次第です）

2023-02-17 08:06 UTC, kanaeta commented on src/main/scala/dev/hiro_hori/digdag_operator_snowflake/SnowOperator.scala
> +      val maxStmt = sql.count(_ == ';')
はい、おっしゃるとおりで、これがunitlではなくtoにしている理由の一つです。

またクエリ内に文の区切りでは無い「;」が現れる可能性もあり、実際のstatementを数えられているとは限りません。(ので、statment数ピッタリのloopはできない可能性がある)

なのでstmtNunではなくmaxStmtという変数名にしてます。

意味的には、可能性のあるstatement数の最大値というのを表したいのですが、もうちょっと変数名長くするか上限という意味を込めてstmtSupとかにした方がわかりやすかったりしますか?

また、もう一つ説明してなかったのですが、stmt.getResultSet() はイテレーションの最後にnullを返すのではなく、最後のresultSetを返し続けます。(test1タスクの例だと最後のstatement:`SELECT * FROM TEST2;`の結果を返し続ける)

まとめると、正確なstatementを数えられないので、loop回数は可能性のあるstatement数の最大分を回し、さらに重複して抽出したstatementは排除するという考えのもとで、実装しました。

そのためunitilではなくtoを、LISTではなくSETを使用しています。

2023-02-17 08:09 UTC, kanaeta commented on README.md
> +`query`|x|ファイルではなくクエリを直接記載|o|x|x
> クエリを直接記載」で十分だと思った次第

こちらは承知です。修正します。

> クエリ内に変数（${...}）を利用することは可能ですか？
に関しては、直感的には
```
td>:
query: ....
```
と同等の仕様だとほとんどの人は考えると思います。ので説明しなくて良いかなと思いました

2023-02-17 08:10 UTC, kanaeta commented on src/main/scala/dev/hiro_hori/digdag_operator_snowflake/SnowOperator.scala
> +      }.toList
> (0 until maxStmt).foeach() で回して .add() していったほうが読みやすいように思います。

こちら修正します。

2023-02-17 08:43 UTC, sxsw00 commented on src/main/scala/dev/hiro_hori/digdag_operator_snowflake/SnowOperator.scala
> +      val maxStmt = sql.count(_ == ';')
> まとめると、正確なstatementを数えられないので、loop回数は可能性のあるstatement数の最大分を回し、さらに重複して抽出したstatementは排除するという考えのもとで、実装しました。 

ここの実装意図がわかるような説明が欲しいと思いました。

2023-02-17 08:46 UTC, kanaeta commented on src/main/scala/dev/hiro_hori/digdag_operator_snowflake/SnowOperator.scala
> +      val maxStmt = sql.count(_ == ';')
ありがとうございます。　
たしかにこれも付け加えないと、なんでこんな実装しているのって？ 思われそうな部分ですね。。

2023-02-17 09:07 UTC, kanaeta commented on src/main/scala/dev/hiro_hori/digdag_operator_snowflake/SnowOperator.scala
> +      }.toList
修正しました  https://github.com/flinters/digdag_operator_snowflake/pull/27/commits/499783261284cd3a5611a4f267843cd5d138ffeb

2023-02-17 09:07 UTC, kanaeta commented on src/main/scala/dev/hiro_hori/digdag_operator_snowflake/SnowOperator.scala
> +      // stmt.getMoreResultsは値がない場合など機能しない。そのため何個のクエリが実行されたか知る方法がなく、";"をカウントして代わりとした
修正しました https://github.com/flinters/digdag_operator_snowflake/pull/27/commits/067d9707889600a2c76d1608708501395a397e0e

2023-02-17 09:07 UTC, kanaeta commented on src/main/scala/dev/hiro_hori/digdag_operator_snowflake/SnowOperator.scala
> +  protected def buildOutputParam(sql: String, queries: List[QueryResult]): Config =
修正しました https://github.com/flinters/digdag_operator_snowflake/pull/27/commits/475226007c87dc9a5b885e475b98eb2e0f913e29

2023-02-17 09:13 UTC, tkawachi commented on src/main/scala/dev/hiro_hori/digdag_operator_snowflake/SnowOperator.scala
> +      val maxStmt = sql.count(_ == ';')
名前は maxStmt （statement のありえる最大数）のまま、値を `count(";") + 1` にして、ループは until で回すのが良いかと思いました。
@sxsw00 のおっしゃるとおりコメントはほしいです。

2023-02-17 09:28 UTC, kanaeta commented on src/main/scala/dev/hiro_hori/digdag_operator_snowflake/SnowOperator.scala
> +      val maxStmt = sql.count(_ == ';')
指摘ありがとうございます.

おっしゃるとおり、確かにmaxStmtではないので嘘ついてますね.. 

失礼しました、レビューの意図勘違いしてたかもしれません

修正しました

2023-02-17 09:34 UTC, tkawachi approved these changes

2023-02-20 04:37 UTC, so-tomoshira approved these changes

2023-02-20 06:34 UTC, merged